name: CI

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install
      - name: Format
        run: pnpm format
      - name: Check format
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add -A
          git commit -m "Formatted by GitHub Actions" || echo "No changes to commit"
          git push
